name: Assign Permissions to Access Secrets
description: GH Actions Automation for creating SA and assigning permissions to access Secrets to it.

inputs:
  secrets_list:
    description: "List of secrets that would be assigned perms"
    required: true


runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3.5.3

  - uses: List files from Github Repository
    script: |
      ls ${GITHUB_ACTION_PATH}/

  - uses: Read File From Calling Repository
    script: |
      echo ${GITHUB_ACTION_PATH}/script.sh

