name: Assign Permissions to Access Secrets
description: GH Actions Automation for creating SA and assigning permissions to access Secrets to it.

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3.5.3

  - id: 'read_secrets'
    uses: pietrobolcato/action-read-yaml@1.1.0
    with:
      config: secrets-config.yaml

  - id: 'print-read-secrets'
    shell: bash
    run: |
      echo read access secrets: ${{ steps.read_secrets.outputs }}
      echo write access secrets: ${{ steps.read_secrets.outputs }}

